### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by allelive** [fikrado/fikrado.py#9]
[●] Sedang masuk ...  
Traceback (most recent call last):
  File "fikrado.py", line 457, in <module>
    login()
  File "fikrado.py", line 107, in login
    br.form['email'] = id
  File "/home/ale/.local/lib/python2.7/site-packages/mechanize/_form_controls.py", line 1963, in __setitem__
    control = self.find_control(name)
  File "/home/ale/.local/lib/python2.7/site-packages/mechanize/_form_controls.py", line 2355, in find_control
    return self._find_control(name, type, kind, id, label, predicate, nr)
  File "/home/ale/.local/lib/python2.7/site-packages/mechanize/_form_controls.py", line 2448, in _find_control
    raise ControlNotFoundError("no control matching " + description)
mechanize._form_controls.ControlNotFoundError: no control matching name 'email'

**Comment by Cynic2** [comment]
No work
